# Example Docker Compose configuration
#
# Use this as a template to set up docker compose, or as guide to set up other
# orchestration services
services:
  server:
    image: boker02/server:latest # TODO: Revert to oxibooru/server for production
    build:
      context: server
      args: 
        # Setting this to `native` can give small performance gains for some 
        # operations such as reverse search, but makes binary less portable.
        # Leave blank to let Rust determine the target architecture. 
        TARGET_CPU:
    depends_on:
      - sql
    environment:
      # These should be the names of the dependent containers listed below,
      # or FQDNs/IP addresses if these services are running outside of Docker
      POSTGRES_HOST: sql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_PORT:
      PORT:
    volumes:
      - "${MOUNT_DATA}:/data"
      - "./server/config.toml:/opt/app/config.toml"
    stop_signal: SIGINT

  frontend:
    image: boker02/frontend:latest # TODO: Revert to oxibooru/frontend for production
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - server
    environment:
      BACKEND_HOST: server
    volumes:
      - "${MOUNT_DATA}:/data:ro"
    ports:
      - "${PORT}:80"

  sql:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - "${MOUNT_SQL}:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
